### ISSUE TITLE
Drupal 8 Module

### ISSUE THREAD

**Issue by mgifford** [miloskroulik/drupal-digital-climate-strike#1]
Worth mentioning that this will only work for Drupal 8.  Any work on moving this to Drupal 7 too?  More sites use D7.

**Comment by miloskroulik** [comment]
Should be relatively easy to port. I might have a time to do that tomorrow, but I doubt it makes sense, since the date is approaching. I'll try to learn from this failure the next time and start coding earlier.

**Comment by mgifford** [comment]
Not a failure at all.  But ya, the earlier this is implemented the easier it is for everyone.

**Comment by miloskroulik** [comment]
Added a note that this is D8 solution.
